version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: nest_mongo_db
    restart: always
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    container_name: nest_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: nestjs
